### ISSUE TITLE
idea for enhancement 

### ISSUE THREAD

**Issue by ytianzaishui** [mxdi9i7/Auto-Closing-Blocks#1]
This extention is great ! I want do develope the same collaspe-closing-blocks extention before I have got this. hhh
It very helpful for reading long long source code!!
My new idea for enhancement  is that I can defind the foldLevel number for collaspe closing like `if` just collaspe if block not function.
for example:
![image](https://user-images.githubusercontent.com/18025841/116836511-5c610280-abf9-11eb-8832-707a76885d8c.png)

By the way ask a question here. How to get the comand argument in executeCommand function?
like `vscode.commands.executeCommand(`editor.foldLevel${i}`);` I wonder how to get this command `editor.foldLevel`...thanks

**Comment by mxdi9i7** [comment]
Thanks for the support, it's been a while since I've developed for vscode, so I already completely forgot the APIs. As for the suggested feature, I will gladly review any PR you submit.
